ecommerce/clientes/urls.py
from django.urls import path

from clientes.views.clientes_view import criar_cliente, login_user, logout_user

app_name = 'clientes'

urlpatterns = [
    path('cadastrar/', criar_cliente, name="criar_cliente"),
    path('entrar/', login_user, name="login"),
    path('sair/', logout_user, name="logout"),
]

ecommerce/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda req: redirect('/produtos/'), name="home"),
    path('admin/', admin.site.urls),
    path('produtos/', include('produtos.urls')),
    path('clientes/', include('clientes.urls'))
]

ecommerce/produtos/urls.py
from django.urls import path

from produtos.views.produtos_view import listar_produtos

app_name = 'produtos'

urlpatterns = [
    path('', listar_produtos, name="listar_produtos"),
]

ecommerce/clientes/models/user.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)

class MyUserManager(BaseUserManager):
    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

ecommerce/produtos/models/categoria.py
from django.db import models

class Categoria(models.Model):
    nome = models.CharField("categoria", max_length=50)

    def __str__(self) -> str:
        return self.nome

ecommerce/produtos/models/produto.py
from django.db import models

from produtos.models.categoria import Categoria

class Produto(models.Model):
    nome = models.CharField(max_length=250)
    preco = models.FloatField()
    categoria = models.ForeignKey(Categoria, on_delete=models.PROTECT)
    criado_em = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.nome

ecommerce/clientes/views/clientes_view.py
from django.shortcuts import redirect, render
from django.urls import reverse
from django.contrib.auth import get_user_model, authenticate, logout, login

def criar_cliente(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user_created = get_user_model().objects.create(
            email=email,
            # password=password
        )
        user_created.set_password(password)
        user_created.save()
        
        return redirect(reverse('clientes:login'))
    return render(request, 'criar_cliente.html')

def login_user(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(
            username=email,
            password=password
        )
        if user:
            login(request, user)
            return redirect('produtos:listar_produtos')
        else:
            print("Usuário ou senha inválida.")

    return render(request, 'login.html')

def logout_user(request):
    logout(request)
    return redirect(reverse('produtos:listar_produtos'))

ecommerce/produtos/views/produtos_view.py
from django.shortcuts import render

from django.contrib import messages

from produtos.models.produto import Produto

def listar_produtos(request):
    produtos = Produto.objects.all().order_by('-criado_em')[:4]
    return render(request, 'listar_produtos.html', {'produtos': produtos})

ecommerce/clientes/templates/criar_cliente.html
{% extends 'base.html' %}
{% block title %}
    Cadastrar Cliente
{% endblock %}
{% block content %}


<div class="container">
    <div class="row">
        <h3>Criar Novo Usuário</h3>
        <form class="row g-3" method="post">
            {% csrf_token %}
            <div class="col-md-6">
                <label for="inputEmail4" class="form-label">Email</label>
                <input type="email" class="form-control" id="email" name="email">
            </div>
            <div class="col-md-6">
                <label for="inputPassword4" class="form-label">Senha</label>
                <input type="password" class="form-control" id="password" name="password">
            </div>
            <div class="col-12">
                <label for="inputAddress" class="form-label">Usuário</label>
                <input type="text" class="form-control" id="usuario" name="usuario" placeholder="Usuário">
            </div>
            <div class="col-12">
                <button type="submit" class="btn btn-primary">Criar</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

ecommerce/clientes/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="container">
    <div class="row">
        <h3>Criar Novo Usuário</h3>
        <form class="row g-3" method="post">
            {% csrf_token %}
            <div class="col-md-6">
                <label for="inputEmail4" class="form-label">Email</label>
                <input type="email" class="form-control" id="email" name="email">
            </div>
            <div class="col-md-6">
                <label for="inputPassword4" class="form-label">Senha</label>
                <input type="password" class="form-control" id="password" name="password">
            </div>
            <div class="col-12">
                <button type="submit" class="btn btn-primary">Entrar</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

ecommerce/produtos/templates/listar_produtos.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    {% for message in messages %}
        <div class="alert alert-{{message.tags}}" role="alert">
            {{message}}
      </div>
    {% endfor %}

    <!-- + VISTOS -->
    <div id="produtos-destaque" class="container pb-5">
        <h3>produtos recentes</h3>
        <div class="row">
            {% for produto in produtos %}
            <div class="col-md-3">
                <a href="#">
                    <div class="card">
                        <img src="{% static 'img/img.jpg' %}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{produto}}</h5>
                            <p class="card-text">
                            <p class="old-price">
                                R$1.798,00
                                <span class="badge text-bg-success">10%</span>
                            </p>
                            <p class="new-price">{{produto.preco}}</p>
                            <p class="info-price">em 1x no cartão</p>
                            </p>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
            
        </div>
    </div>
    <!--  / + VISTOS -->

    <!-- OFERTA -->

    <div id="produtos-promocoes" class="container pt-5">
        <h3>produtos mais vistos no ecommerce</h3>
        <div class="row">
            <div class="col-md-3">
                <a href="#">
                    <div class="card">
                        <div class="cashback d-flex">
                            30% de Cash Back
                        </div>
                        <img src="{% static 'img/img.jpg' %}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">smartwatch lore ipsum ipsum lore</h5>
                            <p class="card-text">
                            <p class="new-price">R$1609,00</p>
                            <p class="info-price">em 1x no cartão</p>
                            </p>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-md-3">
                <div class="card">
                    <div class="cashback d-flex">
                        30% de Cash Back
                    </div>
                    <img src="{% static 'img/img.jpg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">smartwatch lore ipsum ipsum lore</h5>
                        <p class="card-text">
                        <p class="new-price">R$1609,00</p>
                        <p class="info-price">em 1x no cartão</p>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card">
                    <div class="cashback d-flex">
                        30% de Cash Back
                    </div>
                    <img src="{% static 'img/img.jpg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">smartwatch lore ipsum ipsum lore</h5>
                        <p class="card-text">
                        <p class="new-price">R$1609,00</p>
                        <p class="info-price">em 1x no cartão</p>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card">
                    <div class="cashback d-flex">
                        30% de Cash Back
                    </div>
                    <img src="{% static 'img/img.jpg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">smartwatch lore ipsum ipsum lore</h5>
                        <p class="card-text">
                        <p class="new-price">R$1609,00</p>
                        <p class="info-price">em 1x no cartão</p>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-2">
            <div class="col-md-3">
                <a href="#">
                    <div class="card">
                        <div class="cashback d-flex">
                            30% de Cash Back
                        </div>
                        <img src="{% static 'img/img.jpg' %}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">smartwatch lore ipsum ipsum lore</h5>
                            <p class="card-text">
                            <p class="new-price">R$1609,00</p>
                            <p class="info-price">em 1x no cartão</p>
                            </p>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-md-3">
                <div class="card">
                    <div class="cashback d-flex">
                        30% de Cash Back
                    </div>
                    <img src="{% static 'img/img.jpg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">smartwatch lore ipsum ipsum lore</h5>
                        <p class="card-text">
                        <p class="new-price">R$1609,00</p>
                        <p class="info-price">em 1x no cartão</p>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card">
                    <div class="cashback d-flex">
                        30% de Cash Back
                    </div>
                    <img src="{% static 'img/img.jpg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">smartwatch lore ipsum ipsum lore</h5>
                        <p class="card-text">
                        <p class="new-price">R$1609,00</p>
                        <p class="info-price">em 1x no cartão</p>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card">
                    <div class="cashback d-flex">
                        30% de Cash Back
                    </div>
                    <img src="{% static 'img/img.jpg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">smartwatch lore ipsum ipsum lore</h5>
                        <p class="card-text">
                        <p class="new-price">R$1609,00</p>
                        <p class="info-price">em 1x no cartão</p>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /OFERTA -->
{% endblock %}

ecommerce/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css'%} ">
    <title>Loja - {% block title %}{% endblock %}</title>
</head>

<body>
    <header class="header-menu pt-4">
        <div class="container">
            <div
                class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
                <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-white text-decoration-none">
                    Loja Ecommerce
                </a>
                <div class="col-md-5 text-end">
                    <form class="d-flex" role="search">
                        <input class="form-control me-2" type="search" placeholder="Camisa, Televisão, ..."
                            aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Buscar</button>
                    </form>
                </div>
                <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
                    {% if user.is_authenticated %}
                        <p>
                            Olá {{ user.email }}
                            <a href="{% url 'clientes:logout' %}">Sair</a>
                        </p>
                    {% else %}
                    <li>
                        <a class="dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Olá, faça seu login <br>
                            ou cadastre-se
                        </a>
                        <ul class="dropdown-menu dropdown-signin">
                            <li><a class="dropdown-item" href="{% url 'clientes:login' %}">Entrar</a></li>
                            <li><a class="dropdown-item" href="{% url 'clientes:criar_cliente' %}">Criar Conta</a></li>
                        </ul>
                    </li>
                    {% endif %}
                </ul>
                <nav class="navbar navbar-expand-lg">
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link" href="#">para sua empresa</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">baixe o app</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">receba hoje</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">cartão de credito eco</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">marcas próprias</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">produtos internacionais</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">venda na ecommerce</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Oferta</a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </header>

    <main>
        {% block content %}{% endblock %}
    </main>
    <div class="container">
        <footer class="row row-cols-1 row-cols-sm-2 row-cols-md-5 py-5 my-5 border-top">
            <div class="col mb-3">
                <a href="/" class="d-flex align-items-center mb-3 link-dark text-decoration-none">
                    5o Periodo
                </a>
                <p class="text-muted">© 2022</p>
            </div>

            <div class="col mb-3">

            </div>

            <div class="col mb-3">
                <h5>Section</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
                </ul>
            </div>

            <div class="col mb-3">
                <h5>Section</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
                </ul>
            </div>

            <div class="col mb-3">
                <h5>Section</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
                </ul>
            </div>
        </footer>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>